branches:
  only:
    - master
    - travis


language: generic


matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - CI_DEPEND_DIR=https://raw.githubusercontent.com/zhi-wang/ci-depend/master/xenial
        - ARGS="fftw_dir=../fftw tinker_dir=../tinker/source fortran_config=gfortran.mk"


before_install:
  - sudo apt-get install gfortran


script:
  - mkdir -p tinker/source
  - curl $CI_DEPEND_DIR/tinker-350df099/libtinker.a -o tinker/source/libtinker.a

  - mkdir -p fftw/include
  - curl $CI_DEPEND_DIR/fftw/include/fftw3.h -o fftw/include/fftw3.h

  - mkdir -p fftw/lib
  - cd fftw/lib

  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3.a          -o libfftw3.a
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3_threads.a  -o libfftw3_threads.a
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3f.a         -o libfftw3f.a
  - curl $CI_DEPEND_DIR/fftw/lib/libfftw3f_threads.a -o libfftw3f_threads.a

  - ls -l
  - cd ../..

  - gfortran -v
  - g++ -v
  - echo $HOME
  - echo $PWD

  - make -f make/Makefile create_build build=build
  - cd build
  - make $ARGS all -j2
  - make $ARGS info
  - make $ARGS ignore=0 test
